// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvnczmfswbybujmbfdhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bmN6bWZzd2J5YnVqbWJmZGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDU4MDEsImV4cCI6MjA1NDc4MTgwMX0.bk9-nJTL03qdXHqe0CSqU_LSxBlHO06fXs2KHsNcb54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);